### ISSUE TITLE
Can `plum` overload function from external library?

### ISSUE THREAD

**Issue by ImahnShekhzadeh** [beartype/plum#103]
Hi, 

I'd like to overload the function of an external library like this: 

```python
from external_libary.class_A import function_A

def function_B(x: float): # overload `function_A(x: int)`
    return int(x) 
```
A concrete example: 
```python
import torch
from torch.distributions import Uniform

def log_prob(value: torch.Tensor, x: torch.Tensor) # overload `Uniform.lob_prob(value: torch.Tensor)`
    return ...
```

Is this possible in `plum`?

**Comment by wesselb** [comment]
Hey @ImahnShekhzadeh, I see that you've already closed the issue, but I'd like to reply anyway

Extending functions from external libraries is possible provided that the external functions use `plum` already.

For example, if `foo.py` implements

```python
@dispatch
def add(x: int, y: int) -> int:
     return x  + y
```

then another package `bar.py` could do

```python
from foo import add

@add.dispatch
def add(x: float, y: float) -> float:
     return x + y
```

**Comment by ImahnShekhzadeh** [comment]
Hi @wesselb, 

Sorry for having immediately closed the issue, I had figured out a way via `dispatch`. 

Your way sounds interesting, a potential drawback might be that if `foo.py` does *not* implement `add`, then we couldn't overload the function `add` in `bar.py`... 

Best, 
Imahn

**Comment by wesselb** [comment]
@ImahnShekhzadeh Not a problem at all, of course. I'm glad you found a way via `dispatch`. :)

You're totally right about the drawback. If `foo.py` does not implement `add` with `dispatch`, then there might be no clean way to go about it.
