### ISSUE TITLE
`parametric` conflicts with certain usages of customized `__init_subclass__`

### ISSUE THREAD

**Issue by femtomc** [beartype/plum#105]
Hi!

I'm using JAX, and also using `plum` -- in my library, I've define a mixin class called `Pytree` which automatically implements the Pytree interface for classes which mix it in.

It's quite simple:

```python
class Pytree:
    def __init_subclass__(cls, **kwargs):
        jtu.register_pytree_node(
            cls,
            cls.flatten,
            cls.unflatten,
        )

```

If I wish to use this mixin, and `parametric` -- I'm in for problems, I get duplicate registration:

```
ERROR ... ValueError: Duplicate custom PyTreeDef type registration for <class...>
```

I'm not exactly sure why this occurs, but I'm hoping to find a fix -- because I'd like to use parametric classes to guide some of the dispatch in my library functions.

**Comment by PhilipVinc** [comment]
Can you provide a MWE?

**Comment by femtomc** [comment]
Sure! one moment

**Comment by femtomc** [comment]
```python
import abc
import jax.tree_util as jtu
from plum import parametric

class Pytree:
    def __init_subclass__(cls, **kwargs):
        jtu.register_pytree_node(
            cls,
            cls.flatten,
            cls.unflatten,
        )

    @abc.abstractmethod
    def flatten(self):
        raise NotImplementedError

    @classmethod
    def unflatten(cls, data, xs):
        return cls(*data, *xs)
    

@parametric
class Wrapper(Pytree):    
    def flatten():
        return (), ()
    
Wrapper[int]
```

**Comment by PhilipVinc** [comment]
I suspect the issue lies in [this line](https://github.com/beartype/plum/blob/57e11e65cd91cb45a1e66eb6c2e0c19a7f2a1523/plum/parametric.py#L243) which is run after the concrete class `Wrapper[int]`is created (not Wrapper), and we call the `__init_subclass__`you implemented, but `cls`is `Wrapper` instead of `Wrapper[int]`. 

There should be a way to ensure that the proper class is passed there...

**Comment by femtomc** [comment]
Right - this is a bit of a weird setting (in the sense that `__init_subclass__` is actually globally stateful for the original class). I'd suspect this doesn't occur very often in practice -- but it just happens to be a convenient way to do the registration.

I wonder if I could do something on my end to get around it.

**Comment by PhilipVinc** [comment]
Maybe just changing that line in plum to `super(original_class, cls).__init_subclass__(**kw_args)` will fix it. Let me try a bit more...

**Comment by femtomc** [comment]
Thanks for any help!

**Comment by PhilipVinc** [comment]
Yes, this fixes it. I'm preparing a PR.
By the way, for future reference, a smaller repro without jax is

```python
    from plum import parametric

    register = set()

    class Pytree:
        def __init_subclass__(cls, **kwargs):
            if cls in register:
                raise ValueError("duplicate")
            else:
                register.add(cls)

    @parametric
    class Wrapper(Pytree):    
        pass

    Wrapper[int]
```

**Comment by femtomc** [comment]
Sure, one moment.

**Comment by femtomc** [comment]
Or -- rather, what do you want that is different than the MWE I posted above?

**Comment by PhilipVinc** [comment]
Ah ok, that's what you do? 
(I hate to define the flatten/unflatten by hand. I like things like https://github.com/cgarciae/simple-pytree/blob/main/simple_pytree/pytree.py that automatise it and thought you were doing the same and was curious to see an alternative implementation).

**Comment by femtomc** [comment]
Ah right -- I define `unflatten` automatically, but have `flatten` defined custom.
