### ISSUE TITLE
Comparison documentation on default values.

### ISSUE THREAD

**Issue by coady** [beartype/plum#118]
Hi, I'm the maintainer of [multimethod](/coady/multimethod). As of v1.10, it supports default values as described in the [comparison doc](/beartype/plum/blob/master/docs/comparison.md#correct-handling-of-default-values). Thanks.
```python
from multimethod import multimethod

@multimethod
def f(x: int, y: int = 1):
    return y

>>> f(1, 1)
1

>>> f(1, 1.0)
DispatchError: ('f: 0 methods found', [])
```

**Comment by wesselb** [comment]
Hey @coady! Thanks for opening an issue to point this out. We will adjust the docs shortly and let you know when that’s done. :)

**Comment by wesselb** [comment]
I've removed the respective session from the docs. Thanks again for pointing this out!
