### ISSUE TITLE
Multiple functions arguements to be friendly with MyPy

### ISSUE THREAD

**Issue by fatrybl** [beartype/plum#129]
Hello!
I saw many discussions about MyPy friendly dispatching. But none of them answer the question: 
how to dispatch a function with variable number of positional arguments s.t. MyPy wont blame on it ?
i saw this [issue](https://github.com/beartype/plum/issues/89)
and the instruction [here](https://beartype.github.io/plum/integration.html?highlight=mypy)
but there are equal number of arguments in overloaded methods and one needs to type annotate all of them in "dispatch". whereas in my case i have variable number of args in methods. So the final "dispatch" method can not handle this.
If i do not annotate any args in final "dispatch" method, MyPy also blames

for example:
```
from plum import dispatch, overload

@overload
def f(x: int) -> int:
    return x + 1

@overload
def f(x: str) -> str:
    return x

@overload
def f(x: str, y: str) -> str:
    return x + y

@dispatch
def f(x):
    raise NotImplementedError
```

![image](https://github.com/beartype/plum/assets/22779281/5afcc719-f273-45be-bd21-63eb72b0742a)

Sorry, maybe i skipped an answer somehow, but is there a solution ?

**Comment by fatrybl** [comment]
Thank you @wesselb ! So the idea is to list all the args anyway but they can be set to None. It works in my PyCharm with latest MyPy as well

**Comment by wesselb** [comment]
@fatrybl That’s exactly right! Glad to hear that it works for you. :)
