### ISSUE TITLE
feature request: warning on duplicate signatures

### ISSUE THREAD

**Issue by Wouter1** [beartype/plum#155]
I would like to have a feature or way to get warnings or errors if a method with same signature is defined twice

eg
```
class A:
 @dispatch
 def f(self, x:int):
  return 1
 @dispatch
 def f(self, x:int):
  return 2
```

Of course it may be not so obvious as in this example. 
The variables may have different names, or types that look different may turn out to be the same after some evaluation (eg Optional[int] versus Union[int, None])
As it is, the second definition just overrides the first. 

Maybe ```@dispatch``` could have an option eg ```(override=error)``` or something to that effect, so that you get an error message at the duplicate function

**Comment by wesselb** [comment]
@Wouter1 I've added a warning that's displayed every time a method is overwritten! I think that's a great addition. :)

**Comment by PhilipVinc** [comment]
I just tagged v2.4.2, so yes.

**Comment by Wouter1** [comment]
@PhilipVinc top, thanks!
