### ISSUE TITLE
Improve resolution error messages

### ISSUE THREAD

**Issue by PhilipVinc** [beartype/plum#42]
It would be great if we could offer some ' closest methods matches' when hitting an error, similarly to what Julia does.

If @wesselb you pointed me in the right direction, maybe by giving me a starting point of how to guesstimate the closest matches, I can try to finish a PR after that. I will have to take a 6 hours train with little internet on Wednesday so might put myself on that.

**Comment by PhilipVinc** [comment]
@wesselb do you have an idea of how to implement edit distance with plum internals? I can finalise it but I'm a bit unsure of how to use Signatures to do it...

**Comment by nstarman** [comment]
@PhilipVinc is this now resolved, or is this different than the currently printed error message?

**Comment by wesselb** [comment]
Ah, yes, I believe this is now resolved! Thanks @nstarman :)
