### ISSUE TITLE
Transition to pure PyProject.toml

### ISSUE THREAD

**Issue by PhilipVinc** [beartype/plum#58]
Discussion about transitioning to pure `Pyproject.toml` using either setuptools or poetry. 

> @PhilipVinc Probably a question for another issue, but any chance you guys might consider using a [python-poetry](https://python-poetry.org/) based toolchain to manage pyproject.toml? Makes life a bit easier re: dev dependencies, environments, and deployment.

I have a branch to transit plum to a pure `setuptools` + `pyproject.toml` (so not poetry) but was waiting for `pip` to get together and support editable installs. It seems they fixed it a few months ago so might as well open the PR.

This is now much easier to do since plum does no longer use cython.

If you think `poetry` > `setuptools` I'd be happy to know what's the advantage for packaging @tbsexton  ?

**Comment by tbsexton** [comment]
Poetry handles virtual environment instantiation/updating itself, quite nicely, and plays well with e.g. conda environments if the developer/contributor prefers. It will solve dependencies in a really understandable way, with much nicer trees and optional locking behavior. 

I'm happy to fork that branch and PR to demo how poetry would look, though it might be a bit later.

**Comment by PhilipVinc** [comment]
You are describing advantages of poetry as a user-side package manager.
I'm asking about poetry as a developer-side package build backend.

**Comment by tbsexton** [comment]
Not quite: poetry is generally not installed by the users, only the developers/maintainers. It's a toolchain for assisting in library management, installation, and isolation from the rest of the machine. We would get development/documentation/build dependencies fully managed _separately_ from the install/runtime dependencies. 

Loads of features, but this [video](https://www.youtube.com/watch?v=V7UhzA4g2yg) is a decent starting place, along with [this talk](https://www.youtube.com/watch?v=QX_Nhu1zhlg). Poetry even helps manage pypi publishing... users will not notice any changes on their end (still `pip install plum`)

**Comment by wesselb** [comment]
I've had my eye on Poetry for a while now. After checking out those videos, @tbsexton, it seems like it might provide a major quality of life improvement. I think I would consider switching to Poetry! @PhilipVinc, the [3-minute video](https://www.youtube.com/watch?v=V7UhzA4g2yg) linked by @tbsexton gives a nice and short overview. What do you think?

**Comment by PhilipVinc** [comment]
it's good for me

**Comment by wesselb** [comment]
> I would just ask to use standard extra field to declare extra dependencies such as dev dependencies and not the recently introduced groups that are poetry-only and pip-incompatible.

If that means compatibility with both pip and poetry, then that would seem to me as the better option. Good call!

**Comment by tbsexton** [comment]
@PhilipVinc @wesselb That's an interesting use of `extra` for dev dependencies. I would just point out that, while I can't really see a reason it wouldn't work fine, it seems using `extras` for _strictly_ development dependencies is considered somewhat of an anti-pattern? Such that poetry implemented groups specifically to avoid users putting them in `extras`. See [relevant SO post](https://stackoverflow.com/questions/71405744/whats-the-difference-between-extras-and-groups-in-poetry)

From the v1.2 release notes: 
> If your project has additional dependencies meant to add additional functionality at runtime, they should be declared using the ecosystem-standard [extras](https://python-poetry.org/docs/pyproject/#extras) instead. Extras are supported by package build and install tools such as pip.

So, if we transition to using poetry to assist in the development process, and e.g. expect contributors to use poetry, then keeping non-runtime dependencies _away_ from pypi entirely may be beneficial to reduce runtime complexity e.g. for issue triage. The reason I actually brought up poetry in the first place was to use the development dependency `group` to specify all the sphinx plugins/themes that we might like for documentation, but in a place that would never impact a runtime user (installing via pip). 

Do we foresee a situation where we would need development (non-runtime) dependency specification via `extra`?

**Comment by wesselb** [comment]
Thanks, @tbsexton, for the additional details! Having pondered this and having read around a bit more, I might also be coming around to the opinion of using Poetry-only `groups` for dev. dependencies. For users, this wouldn't make a difference. For developers, however, it would necessitate them to use Poetry, which arguably could not be a bad thing. @PhilipVinc, how would you feel about this?

**Comment by PhilipVinc** [comment]
>  for strictly development dependencies is considered somewhat of an anti-pattern?

It might be the case, even though I fail to see exactly why that would be the case (I understand that `extras-requires` was made for adding runtime dependencies, but how does that create problems if you are adding dev-time dependencies?)

However, I think It is important to make the development workflow as welcoming and easy as possible. 
As there is no standard package manager in python, I think that assuming that everybody has poetry is a wrong assumption, and pretending that wannabe-contributors install poetry is not welcoming. (Moreover, groups are something that only exists in poetry 1.2, released officially few days ago, so you also want wannabe-contributors to update their poetry.)

If we insert `sphinx` and `pytest` in a `dev` `extra`, such that they are installed only If someone does `pip install plum-dispatch[dev]` or `poetry install plum-dispatch -e dev` I don't think this clobbers down user installations? Of course I'd never propose making them 'full-fledges' dependencies. 
The difference is just cosmetic with respect to `poetry install plum-dispatch --with dev` but it works with pip as well (me, as well, I don't have poetry installed everywhere).

(BTW, CI is not a concern)

Overall, I love a good tool, and poetry is growing on me, so I am not really against groups. 
However I am just slitghly worried that making poetry 1.2 a kind-of-strict requirement for developing plum might push away other people. Especially given that there is no standard package manager in python.
I think poetry is still used by a minority in the ecosystem ( I myself haven't fully transitioned to using it, and still use, unfortunately, pip).

**Comment by wesselb** [comment]
Hmm, could we write a small script that installs the Poetry dependencies under pip? For example, the script could take everything under `[tool.poetry.group.dev.dependencies]`, write a new version of `pyproject.toml` that pastes the contents of this section for `[dev-dependencies]`, and then runs `pip install`. Then the README could outline a Poetry-based development install and a pip-based development install. Perhaps this is a little bit far fetched...

**Comment by tbsexton** [comment]
@PhilipVinc all awesome points. 

I definitely agree w.r.t. v1.2 being new, and I actually didn't know about generic "groups" until yesterday! :sweat_smile: Dev-dependencies have been around since the ... beginning? ... of poetry, and iirc the "groups" idea just expands on that tooling to make it generalize. I would recommend only using the e.g. `poetry add -D sphinx` syntax since all poetry users would be able to use that (w/o updating, I believe). Updating _does_ have other benefits for our quality-of-life, like the new(ish) plugin system that lets us use Tiangolo's (of FastAPI fame) [`poetry-version-plugin`](https://github.com/tiangolo/poetry-version-plugin) to manage version specification via, say, only the git tag. 

@wesselb I guess the key question boils down to some things we could test out amongst ourselves in a new branch or two: 
- does requiring use of poetry by developers add significant overhead (preventing contribution) that outweighs the quality-of-life improvements poetry provides?
- will the effort of supporting _both_ poetry _and_ non-poetry development workflows reduce overhead (encouraging contribution) enough to outweigh your overhead in continuing to support both workflows (e.g. people submitting pull requests that don't validate dependencies through, say, `poetry.lock`, which could fail your ci/cd tests and have no non-poetry solution? just brainstorming here).

**Comment by wesselb** [comment]
@tbsexton, I would imagine that fully supporting both a Poetry-supported and non-Poetry dev. workflow might come with a fair amount of overhead.

I guess I was imagining some kind of halfway-house, where you don't entirely exclude non-Poetry users. E.g., with a workaround to install dev. dependencies without Poetry and the ability to run test without Poetry, someone would be able to put together a PR on their own. This PR would fail CI/CD tests, as you point out, but at that point we could suggest they use Poetry to fix CI/CD and help them in doing so. Not entirely sure about this option. Just brainstorming all possibilites! @PhilipVinc, would you be happy with something along these lines, or would you prefer that development be possible entirely without Poetry too?
