### ISSUE TITLE
One-liner register

### ISSUE THREAD

**Issue by hgrecco** [beartype/plum#71]
I usually find myself doing something like this:

```python
from somepackage import somefun

@dispatch
def f(x: float):
    return somefun(x)
```

is there a one liner way to do this that does not require defining `f`? Something like:

```python
dispatch("f", (float, ), somefun)
```

As far as I can tell there is no way to do it because you allways take the fuction name from the function, right?

**Comment by wesselb** [comment]
Hey @hgrecco!

What you're after is currently possible:

```python
In [1]: from plum import dispatch

In [2]: def myf(x):
   ...:     print("Go!")
   ...:     return x
   ...:

In [3]: def dispatch_name(name, types, implementation):
   ...:     def temp(*args, **kw_args):
   ...:         return implementation(*args, **kw_args)
   ...:     temp.__name__ = name
   ...:     return dispatch.multi(types)(temp)
   ...:

In [4]: f = dispatch_name("f", (int,), myf)

In [5]: f(1)
Go!
Out[5]: 1

In [6]: f("1")
NotFoundLookupError: For function "f", signature Signature(builtins.str) could not be resolved.
```

However, `dispatch.multi` might be deprecated when Plum 2.0 (#68) comes out. If that happens, then what you're after should still be possible, but the solution might be different from above. I'll make sure to keep this use case in mind! :)

**Comment by wesselb** [comment]
Hey @hgrecco,

With Plum 2.0, the above should still work. But another way is possible too:

```python
from plum import dispatch, Function, Signature


def dispatch_name(name, types, implementation):
    if name not in dispatch.functions:
        dispatch.functions[name] = Function(lambda x: x)
        dispatch.functions[name].__name__ = name
    dispatch.functions[name].register(implementation, Signature(*types))
    return dispatch.functions[name]


square = dispatch_name("square", (int,), lambda x: x * x)

print(square(2))
```

I hope one of these two solutions suffices! Closing this issue for now, but feel free to reopen it if the above solutions aren't satisfactory.
