### ISSUE TITLE
Missing `plum.__version__` attribute

### ISSUE THREAD

**Issue by patrick-kidger** [beartype/plum#78]
This isn't technically necessary, but it's a common convention to define a `__version__` attribute on Python packages, that can be checked at runtime. Currently Plum doesn't define one.

**Comment by pabloferz** [comment]
AFAICT, the only way to access this for now is like this:
```python
from plum._version import __version__ as __plum_version__
```

**Comment by wesselb** [comment]
I believe #79 by @PhilipVinc should have addressed this. :)
