### ISSUE TITLE
Adding a few type hints to the codebase

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [beartype/plum#90]
Hi there. I'm currently diving in the plum codebase because I'd like to implement this: https://github.com/beartype/plum/issues/40#issuecomment-1668350255 . I work with pycharm and pycharm has quite a hard time jumping to source because there are no type hints anywhere. Would you be open to have a pull request that adds a few type hints to the codebase? It would allow me to understand it better and for future contributors to have an easier time with their IDEs.

**Comment by wesselb** [comment]
Hey @gabrieldemarmiesse! Wouldn't mind that at all. On the contrary, this would be very welcome. :) I think we'll have a hard time making the code base `mypy`-compliant because the package internals use multiple dispatch, but type hints will be helpful nevertheless.

**Comment by wesselb** [comment]
Closing this since the majority of your contributions are now merged. :)
