### ISSUE TITLE
Interaction with `inspect`

### ISSUE THREAD

**Issue by femtomc** [beartype/plum#98]
I'm using multi-methods from `plum` in my library. One issue I've had is that `inspect` has a difficult time with `_BoundFunction` -- e.g. `inspect.getfile` will break on `_BoundFunction`. What's the proper way to deal with this? Should I forward `inspect.getfile` to `_BoundFunction._f`?

**Comment by wesselb** [comment]
Hey @femtomc! Yes, I think forwarding inspect.getfile to `_BoundFunction._f._f` sounds very sensible (note the double `_f`). This will show the place where the function is defined for the first time. Is it easy to redirect inspect.getfile to this?

**Comment by femtomc** [comment]
Closing this — as yes, it was :)
